openapi: 3.0.3
info:
  title: kc3_2021_g
  version: 0.0.0
servers:
  - url: https://example.com
    description: モックサーバー
  - url: http://localhost:8080
    description: ローカル環境
tags:
  - name: hoge

paths:
  /hoge:
    get:
      tags:
        - hoge
      summary: ''
      # security:
      #   - Admin: []
      responses:
        200:
          $ref: '#/components/responses/200'

components:
  schemas:
    Id:
      type: integer
      minimum: 1
      example: 1

    Time:
      type: string
      format: HH:MM:SS
      example: '12:59:59'

    Datetime:
      type: string
      format: date-time
      example: 2020-01-01T12:59:59Z

    URL:
      type: string
      format: url
      example: 'https://example.com'

  responses:
    200:
      description: OK
    201:
      description: Created
    204:
      description: No Content
    400:
      description: Bad Request
    401:
      description: Unauthorized
    403:
      description: ForbIdden
    404:
      description: Not Found
    cors:
      description: Default response for CORS method
      headers:
        Access-Control-Allow-Headers:
          schema:
            type: 'string'
        Access-Control-Allow-Methods:
          schema:
            type: 'string'
        Access-Control-Allow-Origin:
          schema:
            type: 'string'

  securitySchemes:
    Admin:
      type: apiKey
      name: Authorization
      in: header
      description: IDトークンを付与

    Firebase:
      type: apiKey
      name: Authorization
      in: header
      description: IDトークンを付与
